config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'home/index'
	
	devise_for :users
	root to: "home#index"

	resources :products
	resources :carts, only: [:index, :destroy]
	get "add_to_cart/:product_id", to: 'carts#add_to_cart', as: 'add_to_cart'


	# resource :users do
		
	# end

	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :products  
end

app/models/chart.rb
class Chart < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploaders :product_images, ProductImagesUploader
  belongs_to :user
  has_and_belongs_to_many :carts
  validates :name, presence: true
  validates :price, presence: true
  validates :product_images, presence: true

  scope :published_products, ->{ where(published: true) }
  #scope :fetch_products,  -> (id){ find_by(id: id) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
  has_one :cart


  after_create :create_cart

  private

  def create_cart
  	create_cart!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :user_type, :password, :password_confirmation])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_cart

  def index
    @products = @cart.products
  end
  
  def add_to_cart
    @cart.products << Product.find(params[:product_id])
    
    if @cart.save
      flash[:success] = "Product added to cart"
      redirect_to root_path 
    else
      render 'new'
    end
    #byebug
  end

  def destroy
    product = Product.find_by(id: params[:id])
    @cart.products.delete(product)
    flash[:success] = "Product added to cart"
    redirect_to carts_path 
  end



  private

  def get_cart
    @cart = current_user.cart
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @product = Product.published_products
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, except: [:index, :new, :create]
  
  def index
    @products = current_user.products
  end
  
  def new
    @product = Product.new
  end

  def create
    @product = current_user.products.new(get_params)
    if @product.save
      flash[:success] = "Product has been added"
      redirect_to products_path
    else
      flash[:error] = "Issue with add product"
      render 'new'
    end
  end


  def update
    if @product.update(get_params)
      flash[:success] = "Product has been added"
      redirect_to product_path(@product)
    else
      flash[:error] = "Issue with add product"
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    flash[:success] = "Product has been deleted"
    redirect_to products_path
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end
  def get_params
    params["product"]["product_images"] = params["product"]["product_images"].first(3) if params["product"]["product_images"].present? 
    params.require(:product).permit(:name, :price, :description, {product_images: []})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_button
    if user_signed_in?
      link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link'
    else
      link_to 'Login', new_user_session_path, class: 'nav-link'
    end
  end 
  def add_product_button
    link_to 'Add new product', new_product_path, class: 'nav-link'
  end
  def cart_button
    link_to 'My Cart', carts_path, class: 'nav-link'
  end
  def account_seller_type?
    return (current_user.present? && current_user.user_type == 'seller')   
  end
  def account_buyer_type?
    return current_user.present? && current_user.user_type == 'buyer'   
  end

  def image_url(product)
     product.product_images.present? ? product.product_images.first.url : 'place_holder.jpg' 
   end 
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def form_submit_button
    action_name == 'new' ? 'Add Product' : 'Update Product'
  end  
end

app/views/carts/index.html.erb
<h1>Products Page</h1>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Links</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>
        <td>
          <%= link_to 'Show', product_path(product) %>
          <%= link_to 'Destroy', cart_path(product),
              method: :delete,
              data: { confirm: 'Are you sure?' }
           %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<h1>BUY Products</h1>

<div class = 'row'>
  <% @product.each do |product| %>
    <div class= 'col-xs-3 p-5'>
      <%= image_tag image_url(product), width: 200, height: 200 %>
      <p><strong>Seller Name:</strong><%= product.user.name %></p>
      <p><strong>Product Name:</strong><%= product.name %></p>
      <p><strong>Product Price:</strong><%= product.price %></p>
      <%= link_to 'Add to Chart', add_to_cart_path(product) if account_buyer_type? %>
    </div>
    
  <% end %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcommerceApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
      <% if flash.present? %>
        <p class="flash-errors"><%= flash[:error] %></p>
        <p class="flash-success"><%= flash[:success] %></p>
        <p class="flash-notice"><%= flash[:notice] %></p>
      <% end %>

      <%if notice.present? || alert.present? %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      <% end %>
      
      
      
      <%= render 'shared/header' %>
    <div class= 'container'>
      <%= yield %>  
    </div>
  </body>
</html>

app/views/products/_shared_form.html.erb
<%= form_for @product do |f| %>
  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :price %><br />
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br />
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :product_images %><br />
    <%= f.file_field :product_images, multiple: true, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit form_submit_button, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Product Edit</h1>
<%= render 'products/shared_form' %>

app/views/products/index.html.erb
<h1>Products Page</h1>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Published Status</th>
      <th>Links</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>
        <td><%= product.published %></td>
        <td>
          <%= link_to 'Show', product_path(product) %>
          <%= link_to 'Edit', edit_product_path(product) %>
          <%= link_to 'Destroy', product_path(product),
              method: :delete,
              data: { confirm: 'Are you sure?' }
           %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h2>Add new product</h2>

<%= render 'products/shared_form' %>

<%#= render "devise/shared/links" %>

app/views/products/show.html.erb
<h2>Product Show Page</h2>
<p>
  <strong>Id:</strong>
  <%= @product.id %>
</p>
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>
<table>
  <tbody>
    <tr>
      <% @product.product_images.each do |image| %>
        <td>
          <%= image_tag image.url, height: 200, width: 200 %>
        </td>
      <% end %>
    </tr>
  </tbody>
</table>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Ecommerce App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav my-4 my-lg-0">
      <li class="nav-item">
        <%= account_seller_type? ? add_product_button : cart_button %>
      </li>
      <li class="nav-item">
        <%= link_to 'My Products', products_path, class: 'nav-link' if account_seller_type? %>
      </li>
      <li class="nav-item">
        <%= login_button %>
      </li>
    </ul>
  </div>
</nav>